### ISSUE TITLE
Gurobi license assignment not working for single user?

### ISSUE THREAD

**Issue by larsvilhuber** [p-b-j/uscb-das-container-public#1]
When I run this on workstation, I get
```
info  : You have asked to assign this single user license to user 'root', this is unusual
Assign license to user 'root' on this machine? [Y/n] 
error : ERROR 993: Internal error, contact support
```
Have you encountered this?

**Comment by p-b-j** [comment]
Ah it appears the license I was using didn't have this issue, but can confirm that I get the same error using a fresh license.

I took a little closer look and the Gurobi license really isn't needed for the container build, so I've just pushed a change that removes the license download from the Dockerfile. Could you try again w/the new change and see if you are able to build now?

Separately, I'll open a new issue since the Dockerfile should really be cleaned up a bit more (but I think the above change should allow you to build a working image).

**Comment by larsvilhuber** [comment]
I actually addressed this (successfully) a different way, see https://github.com/p-b-j/uscb-das-container-public/pull/2/commits/aa0c4913242449744463c8077162a885d768c720 (PR #2)

**Comment by p-b-j** [comment]
Ah I see, glad it's working! I'll close this issue then
